import { Locale } from '../locales/types';

export interface LocaleDefaults {
  title: string;
  names: string;
  locationName: string;
  lat: number;
  lng: number;
  dateStr: string;
  coords: string;
}

export const LOCALE_DEFAULTS: Record<Locale, LocaleDefaults> = {
  nl: {
    title: 'DE NACHT WAARIN WE ELKAAR VONDEN',
    names: 'Sophie & Daan',
    locationName: 'Amsterdam, Nederland',
    lat: 52.3676,
    lng: 4.9041,
    dateStr: '22 SEPTEMBER 2026',
    coords: '52.3676° N • 4.9041° E',
  },
  de: {
    title: 'DIE NACHT, IN DER WIR UNS TRAFEN',
    names: 'Hannah & Maximilian',
    locationName: 'Berlin, Deutschland',
    lat: 52.5200,
    lng: 13.4050,
    dateStr: '22. SEPTEMBER 2026',
    coords: '52.5200° N • 13.4050° O',
  },
  en: {
    title: 'THE NIGHT WE MET',
    names: 'Olivia & James',
    locationName: 'London, United Kingdom',
    lat: 51.5074,
    lng: -0.1278,
    dateStr: 'SEPTEMBER 22, 2026',
    coords: '51.5074° N • 0.1278° W',
  },
};

export const ALL_KNOWN_TITLES = new Set([
  'de sterrenhemel boven',
  'de nacht waarin we elkaar vonden',
  'onze huwelijksdag',
  'welkom op de wereld',
  'onder dezelfde sterren',
  'de dag dat wij begonnen',
  'onze eerste kus',
  'de dag dat jij geboren werd',
  'onze trouwdag',
  'de nacht dat onze wereld veranderde',
  'waar onze reis begon',
  'geschreven in de sterren',
  'the night we met',
  'our wedding day',
  'welcome to the world',
  'under the same stars',
  'the sky when we met',
  'the day you were born',
  'our first kiss',
  'where our story began',
  'written in the stars',
  'the night our stars aligned',
  'der nachthimmel über',
  'die nacht, in der wir uns trafen',
  'unser hochzeitstag',
  'willkommen auf der welt',
  'unter den gleichen sternen',
  'der himmel als wir uns trafen',
  'der tag an dem du geboren wurdest',
  'unser erster kuss',
  'wo unsere geschichte begann',
  'in den sternen geschrieben',
  'der moment in dem wir eins wurden',
]);

export const ALL_KNOWN_NAMES = new Set([
  'emma & lucas',
  'sophie & thomas',
  'emma & liam',
  'sophie & daan',
  'hannah & maximilian',
  'olivia & james',
  'laura & felix',
  'charlotte & william',
  'liam alexander',
  'noah alexander',
  'oliver james',
  'mila & thomas',
  'mia & jonas',
  'amelia & george',
]);

export const ALL_KNOWN_DATES = new Set([
  '21 juni 2024',
  'june 21, 2024',
  '21. juni 2024',
  '22 september 2024',
  'september 22, 2024',
  '22. september 2024',
  '22 september 2026',
  'september 22, 2026',
  '22. september 2026',
  '18 augustus 2023',
  'august 18, 2023',
  '18. august 2023',
  '14 mei 2025',
  'may 14, 2025',
  '14. mai 2025',
  '04 oktober 2020',
  'october 04, 2020',
  '04. oktober 2020',
  '03 oktober 2021',
]);

export const ALL_KNOWN_LOCATIONS = new Set([
  'amsterdam, nederland',
  'london, united kingdom',
  'berlin, deutschland',
  'utrecht, nederland',
  'rotterdam, nederland',
  'antwerpen, belgië',
  'den haag, nederland',
  'münchen, deutschland',
  'hamburg, deutschland',
  'köln, deutschland',
  'wien, österreich',
  'zürich, schweiz',
  'new york, united states',
  'paris, france',
  'dublin, ireland',
  'edinburgh, united kingdom',
  'gent, belgië',
  'eindhoven, nederland',
  'brussel, belgië',
  'amsterdam',
  'utrecht',
  'rotterdam',
  'den haag',
  'berlin',
  'london',
  'münchen',
  'hamburg',
  'köln',
  'wien',
  'zürich',
  'new york',
  'paris',
  'dublin',
  'edinburgh',
]);

export const ALL_KNOWN_COORDS = new Set([
  '52.3676° n • 4.9041° e',
  '51.5074° n • 0.1278° w',
  '52.5200° n • 13.4050° e',
  '52.5200° n • 13.4050° o',
  '52.0907° n • 5.1214° e',
  '55.9533° n • 3.1883° w',
  '48.1351° n • 11.5820° o',
  '48.1351° n • 11.5820° e',
  '53.5511° n • 9.9937° o',
  '53.5511° n • 9.9937° e',
  '53.3498° n • 6.2603° w',
  '51.9244° n • 4.4777° e',
  '48.2082° n • 16.3738° o',
  '48.2082° n • 16.3738° e',
  '40.7128° n • 74.0060° w',
  '51.2194° n • 4.4025° e',
  '52.0705° n • 4.3007° e',
]);
