import { ProductItem } from '../types';

export const PRODUCTS: ProductItem[] = [
  {
    id: 'celestial-blueprint',
    title: 'The Celestial Blueprint™',
    tagline: 'Custom Astronomical Star Map',
    description:
      'Scientifically calculated using NASA JPL ephemeris. Captures the exact, breathtaking night sky above any place and milestone moment in time.',
    price: '$49.00',
    originalPrice: '$68.00',
    rating: 4.98,
    reviewCount: 2840,
    badge: 'FLAGSHIP KEEPSAKE',
    image: '/textures/star_map_sample.png',
    category: 'celestial',
    available: true,
    material: '300 DPI Archival 285gsm Cotton Rag Paper',
    details: [
      'Calculated via Skyfield astronomy algorithms',
      '8,870 visible Hipparcos catalog stars & 88 constellations',
      'Choice of Scandinavian oak, matte black, or white gallery framing',
      'Instant interactive preview & high-resolution proof',
    ],
  },
  {
    id: 'heritage-walnut-box',
    title: 'The Heritage Keepsake Box',
    tagline: 'Hand-Carved Solid Walnut & Brass',
    description:
      'Sustainably harvested American walnut hand-planed and conditioned with organic beeswax. Precision-engraved with your milestone date, couple monogram, or private vows inside the lid.',
    price: '$78.00',
    originalPrice: '$95.00',
    rating: 4.97,
    reviewCount: 620,
    badge: 'SOLID HARDWOOD',
    image: '',
    category: 'wood',
    available: false,
    material: 'Solid American Walnut & Brushed Brass Hardware',
    details: [
      'Handcrafted joinery with mortise & tenon corners',
      'Velvet-lined bottom tray for rings, watches, and heirloom letters',
      'Custom laser engraving with your personal inscription',
      'Finished with food-safe non-toxic natural beeswax',
    ],
  },
  {
    id: 'monogram-cloud-socks',
    title: 'Embroidered Monogram Cloud Socks',
    tagline: 'Set of 2 Organic Combed Cotton',
    description:
      'Sumptuously soft organic cloud-cotton socks delicately embroidered with handwritten initials, Roman numeral anniversary dates, or a discreet love note at the ankle.',
    price: '$28.00',
    originalPrice: '$38.00',
    rating: 4.96,
    reviewCount: 1480,
    badge: 'ORGANIC COTTON',
    image: '',
    category: 'socks',
    available: false,
    material: '100% Certified Organic Long-Staple Cotton',
    details: [
      'Bespoke needlework embroidery at our studio',
      'Seamless toe construction for cloud-like all-day comfort',
      'Gift-ready in recycled kraft paper band & wax seal',
      'Pre-washed and shrink-resistant natural dyes',
    ],
  },
  {
    id: 'solstice-calendar-plaque',
    title: 'The Solstice Milestone Plaque',
    tagline: 'Sculpted European Beech & Brass',
    description:
      'A quiet, minimalist desktop sculpture honoring a single life-altering day. Sculpted from solid European beechwood with an inset magnetic brass ring marking your exact date.',
    price: '$54.00',
    originalPrice: '$68.00',
    rating: 4.94,
    reviewCount: 430,
    badge: 'STUDIO CRAFT',
    image: '',
    category: 'wood',
    available: false,
    material: 'Sustainably Sourced European Beech & Solid Cast Brass',
    details: [
      'Minimalist perpetually positioned calendar marker',
      'Laser-etched anniversary coordinates or couple names on the base',
      'Heavy weighted base with anti-scratch wool felt footing',
      'Timeless heirloom gift for desks, nightstands, and mantels',
    ],
  },
  {
    id: 'true-north-map',
    title: 'True North: Coordinates Art',
    tagline: 'Architectural Line Cartography',
    description:
      'An exquisitely refined architectural street map centered on the precise latitude and longitude of where you met, got engaged, or built your home.',
    price: '$45.00',
    originalPrice: '$60.00',
    rating: 4.95,
    reviewCount: 1120,
    badge: 'WARM MINIMALIST',
    image: '',
    category: 'cartography',
    available: false,
    material: 'Heavyweight Matte Archival Paper',
    details: [
      'Custom street geometry for any global address or landmark',
      'Minimalist compass rose & clean typographic coordinates',
      'Museum-grade fade-resistant pigment inks',
    ],
  },
  {
    id: 'leather-vow-journal',
    title: 'The Heirloom Vow Journal',
    tagline: 'Vegetable-Tanned Italian Leather',
    description:
      'Supple full-grain Tuscan leather hand-bound with raw Irish linen thread. Contains deckle-edge cotton paper, blind-debossed with your family name or personal vows.',
    price: '$64.00',
    originalPrice: '$82.00',
    rating: 4.98,
    reviewCount: 780,
    badge: 'HAND-STITCHED',
    image: '',
    category: 'leather',
    available: false,
    material: 'Tuscan Full-Grain Vegetable-Tanned Leather',
    details: [
      '160 pages of acid-free handmade deckle-edge paper',
      'Wraparound leather strap with brass stud closure',
      'Ages gracefully with a rich, unique patina over decades',
    ],
  },
];
