import { StyleOption } from '../types';

export const DESIGN_STYLES: StyleOption[] = [
  {
    id: 'midnight_classic',
    name: 'Midnight Classic',
    subtitle: 'Atelier Signature Bestseller',
    description: 'Deep navy celestial sphere with dual compass ring, degree ticks & luminous stars',
    bgColor: '#0B132B',
    mapBgColor: '#070D1F',
    starColor: '#FFFFFF',
    constellationColor: 'rgba(255, 255, 255, 0.38)',
    maskShape: 'circle',
    borderColor: 'rgba(255, 255, 255, 0.45)',
    ringColor: 'rgba(255, 255, 255, 0.25)',
    textColor: '#FFFFFF',
    subtitleColor: 'rgba(255, 255, 255, 0.85)',
    footerColor: 'rgba(255, 255, 255, 0.65)',
    curvedText: false,
    constellationsOnly: false,
  },
  {
    id: 'teal_watercolor',
    name: 'Teal Watercolor',
    subtitle: 'Organic Nebula Atmosphere',
    description: 'Swirling deep marine teal & cyan watercolor mask on matted linen background',
    bgColor: '#F5F7F6',
    mapBgColor: '#083B44',
    starColor: '#FFFFFF',
    constellationColor: 'rgba(255, 255, 255, 0.42)',
    maskShape: 'circle',
    borderColor: '#0C4B56',
    ringColor: 'rgba(12, 75, 86, 0.3)',
    textColor: '#083B44',
    subtitleColor: '#1A5A66',
    footerColor: '#3B7580',
    curvedText: false,
    constellationsOnly: false,
    isWatercolor: true,
  },
  {
    id: 'emerald_night',
    name: 'Emerald Night',
    subtitle: 'British Racing Green & Royal Gold',
    description: 'Deep forest green backdrop, metallic gold stars (#D4AF37) & golden celestial dials',
    bgColor: '#081C15',
    mapBgColor: '#04110C',
    starColor: '#D4AF37',
    constellationColor: 'rgba(212, 175, 55, 0.45)',
    maskShape: 'circle',
    borderColor: '#D4AF37',
    ringColor: 'rgba(212, 175, 55, 0.3)',
    textColor: '#D4AF37',
    subtitleColor: '#F3E5AB',
    footerColor: '#C9B06B',
    curvedText: false,
    constellationsOnly: false,
  },
  {
    id: 'burgundy_sky',
    name: 'Burgundy Sky',
    subtitle: 'Velvet Wine & Champagne Rose',
    description: 'Rich romantic wine red, sparkling white stars & delicate warm rose-gold ring accents',
    bgColor: '#38070E',
    mapBgColor: '#240308',
    starColor: '#FFFFFF',
    constellationColor: 'rgba(255, 255, 255, 0.38)',
    maskShape: 'circle',
    borderColor: 'rgba(255, 235, 238, 0.4)',
    ringColor: 'rgba(255, 235, 238, 0.22)',
    textColor: '#FFFFFF',
    subtitleColor: '#F7D6DA',
    footerColor: '#D6A6AD',
    curvedText: false,
    constellationsOnly: false,
  },
];

export const GOOGLE_FONTS = [
  { id: 'Playfair Display', name: 'Playfair Display', fontClass: 'font-playfair', category: 'Romantic Serif', sample: 'The Night We Met' },
  { id: 'Montserrat', name: 'Montserrat', fontClass: 'font-montserrat', category: 'Modern Geometric Sans', sample: 'OUR FIRST DATE' },
  { id: 'Cinzel', name: 'Cinzel', fontClass: 'font-cinzel', category: 'Classic Roman Capitals', sample: 'UNDER THE STARS' },
  { id: 'Great Vibes', name: 'Great Vibes', fontClass: 'font-greatvibes', category: 'Elegant Script Calligraphy', sample: 'Emma & Noah' },
  { id: 'Lato', name: 'Lato', fontClass: 'font-lato', category: 'Clean Scandinavian Sans', sample: 'September 22, 2026' },
];

export const POPULAR_LOCATIONS = [
  { name: 'Amsterdam, Nederland', lat: 52.3676, lon: 4.9041 },
  { name: 'Rotterdam, Nederland', lat: 51.9244, lon: 4.4777 },
  { name: 'Utrecht, Nederland', lat: 52.0907, lon: 5.1214 },
  { name: 'Antwerpen, België', lat: 51.2194, lon: 4.4025 },
  { name: 'Brussel, België', lat: 50.8503, lon: 4.3517 },
  { name: 'Gent, België', lat: 51.0543, lon: 3.7174 },
  { name: 'Brugge, België', lat: 51.2093, lon: 3.2247 },
  { name: 'Eindhoven, Nederland', lat: 51.4416, lon: 5.4697 },
  { name: 'Parijs, Frankrijk', lat: 48.8566, lon: 2.3522 },
];

export const getLocalizedStyleDetails = (locale: string = 'nl') => {
  const map: Record<string, Record<string, { title: string; subtitle: string; desc: string; tag: string }>> = {
    nl: {
      midnight_classic: {
        title: 'Midnight Classic',
        subtitle: 'Onze Meest Geliefde Bestseller',
        desc: 'Diep koningsblauw met dubbele kompasring, fijne graadverdeling en fonkelende witte sterren.',
        tag: 'BESTSELLER',
      },
      teal_watercolor: {
        title: 'Teal Watercolor',
        subtitle: 'Zachte Aquarel & Neveltextuur',
        desc: 'Sfeervolle marineblauwe en cyaankleurige aquarelstructuur op een warm linnenachtergrond.',
        tag: 'ARTISTIEK',
      },
      emerald_night: {
        title: 'Emerald Night',
        subtitle: 'Brits Bosgroen & Koninklijk Goud',
        desc: 'Diepgroene nachthemel gecombineerd met metallic gouden sterren en hemelcoördinaten.',
        tag: 'LUXE EDITIE',
      },
      burgundy_sky: {
        title: 'Burgundy Sky',
        subtitle: 'Warme Romantiek & Fluweelrood',
        desc: 'Rijke bordeauxrode tinten die liefde en warmte uitstralen, afgewerkt met zachte parelwitte typografie.',
        tag: 'ROMANTISCH',
      },
    },
    de: {
      midnight_classic: {
        title: 'Midnight Classic',
        subtitle: 'Unser Beliebtester Bestseller',
        desc: 'Tiefes Königsblau mit doppeltem Kompassring, feinen Gradteilungen und funkelnden Sternen.',
        tag: 'BESTSELLER',
      },
      teal_watercolor: {
        title: 'Teal Watercolor',
        subtitle: 'Sanfte Aquarell- & Nebeltextur',
        desc: 'Stimmungsvolle marine- und cyanblaue Aquarellstruktur auf warmem Hintergrund.',
        tag: 'KÜNSTLERISCH',
      },
      emerald_night: {
        title: 'Emerald Night',
        subtitle: 'Waldgrün & Edles Gold',
        desc: 'Dunkelgrüner Nachthimmel kombiniert mit edlen goldenen Sternen und Himmelskoordinaten.',
        tag: 'LUXUS EDITION',
      },
      burgundy_sky: {
        title: 'Burgundy Sky',
        subtitle: 'Warme Romantik & Samtrot',
        desc: 'Satte bordeauxrote Nuancen, die Liebe und Wärme ausstrahlen, veredelt mit Perlweiß.',
        tag: 'ROMANTISCH',
      },
    },
    en: {
      midnight_classic: {
        title: 'Midnight Classic',
        subtitle: 'Our Most Beloved Bestseller',
        desc: 'Deep royal navy with double compass dial, delicate degree ticks, and luminous white stars.',
        tag: 'BESTSELLER',
      },
      teal_watercolor: {
        title: 'Teal Watercolor',
        subtitle: 'Gentle Nebula Watercolor Texture',
        desc: 'Atmospheric deep teal and cyan watercolor structure across a warm matted background.',
        tag: 'ARTISTIC',
      },
      emerald_night: {
        title: 'Emerald Night',
        subtitle: 'British Racing Green & Royal Gold',
        desc: 'Deep forest green night sky paired with metallic gold celestial coordinates.',
        tag: 'LUXURY EDITION',
      },
      burgundy_sky: {
        title: 'Burgundy Sky',
        subtitle: 'Warm Romance & Velvet Crimson',
        desc: 'Rich burgundy hues radiating warmth and devotion, finished with soft pearl typography.',
        tag: 'ROMANTIC',
      },
    },
  };
  return map[locale] || map.nl;
};
